export const PlantillaDiagramaDeFlujo = {
    name: 'Diagrama de Flujo',
    image: '/templates/diagrama-de-flujo.png',
    href: "/plantillas/diagrama-de-flujo/",
    layers: {
        "1q7ytAzhyyx5OmWBD3jHl": {
            center: { x: 439, y: 477 },
            endArrowHead: "Triangle",
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 0,
            type: 6,
            width: 84,
            x: 393,
            y: 477,
        },
        "6Wz6MCEBXO5t5eX6OBkPW": {
            fill: { a: 1, b: 177, g: 249, r: 255 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 24,
            type: 4,
            value: "Inicio",
            width: 150,
            x: 241,
            y: 431,
        },
        "7XpF75ziVyidAFJ9dcksT": {
            center: { x: 1045, y: 570 },
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 86,
            type: 6,
            width: 0,
            x: 1045,
            y: 527,
        },
        HyE0alujPY4OUaTdSN6ZW: {
            fill: { a: 1, b: 99, g: 202, r: 68 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 12,
            type: 4,
            width: 150,
            x: 726,
            y: 618.5,
        },
        IhUnWFNjnrDhEN0r0LIW6: {
            fill: { a: 1, b: 99, g: 202, r: 68 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 12,
            type: 4,
            width: 150,
            x: 969.5,
            y: 431.5,
        },
        JRcVIxmgh2MIjyrsaAdUL: {
            center: { x: 802, y: 276 },
            endArrowHead: "Triangle",
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: -149,
            type: 6,
            width: 272,
            x: 801,
            y: 426,
        },
        cTGsfrhtzEXJVryoYQ9KO: {
            center: { x: 1277.5, y: 278 },
            endArrowHead: "Triangle",
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 0,
            type: 6,
            width: 84,
            x: 1231.5,
            y: 278,
        },
        hOevBFvViZT5hLaZ71OVQ: {
            fill: { a: 1, b: 255, g: 255, r: 255 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 24,
            type: 4,
            value: "Proceso",
            width: 150,
            x: 726,
            y: 431.5,
        },
        j4slR1D6tGqLRSjFdpvmi: {
            center: { x: 682, y: 477 },
            endArrowHead: "Triangle",
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 0,
            type: 6,
            width: 84,
            x: 636,
            y: 477,
        },
        nrHChkGW3xfm6f6JnNiyI: {
            fill: { a: 1, b: 237, g: 142, r: 39 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 24,
            type: 4,
            value: "Fin",
            width: 149.7625082259051,
            x: 1322.737491774095,
            y: 231.5,
        },
        ny5A0TyBrW8hHvA7mScvn: {
            center: { x: 801, y: 573 },
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: -86,
            type: 6,
            width: 0,
            x: 801,
            y: 616,
        },
        pTI7jZhVDXlhJ0vW96EU9: {
            center: { x: 924, y: 664 },
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 0,
            type: 6,
            width: -88,
            x: 968,
            y: 664,
        },
        sRYSgYgnD0kvBHRSph1Pc: {
            fill: { a: 1, b: 237, g: 142, r: 39 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 12,
            type: 4,
            width: 150,
            x: 1079,
            y: 231.5,
        },
        sRmMYXL5CDxvIbk7StHNR: {
            fill: { a: 1, b: 42, g: 142, r: 252 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 12,
            type: 4,
            width: 150,
            x: 484,
            y: 430.5,
        },
        sb44FYQSeSOXFhZ57Jkwq: {
            center: { x: 924.5, y: 478 },
            endArrowHead: "Triangle",
            fill: { a: 0, b: 0, g: 0, r: 0 },
            height: 0,
            type: 6,
            width: 84,
            x: 878.5,
            y: 478,
        },
        xdsRlOvS3LhHdpGOeOFdp: {
            fill: { a: 1, b: 99, g: 202, r: 68 },
            height: 93,
            outlineFill: { a: 1, b: 1, g: 1, r: 1 },
            textFontSize: 12,
            type: 4,
            width: 150,
            x: 971,
            y: 619.5,
        },
    },
    layerIds: [
        "6Wz6MCEBXO5t5eX6OBkPW",
        "1q7ytAzhyyx5OmWBD3jHl",
        "j4slR1D6tGqLRSjFdpvmi",
        "sRmMYXL5CDxvIbk7StHNR",
        "hOevBFvViZT5hLaZ71OVQ",
        "JRcVIxmgh2MIjyrsaAdUL",
        "sRYSgYgnD0kvBHRSph1Pc",
        "cTGsfrhtzEXJVryoYQ9KO",
        "nrHChkGW3xfm6f6JnNiyI",
        "sb44FYQSeSOXFhZ57Jkwq",
        "IhUnWFNjnrDhEN0r0LIW6",
        "7XpF75ziVyidAFJ9dcksT",
        "xdsRlOvS3LhHdpGOeOFdp",
        "pTI7jZhVDXlhJ0vW96EU9",
        "HyE0alujPY4OUaTdSN6ZW",
        "ny5A0TyBrW8hHvA7mScvn",
    ]
};